# Generated by Django 5.2.6 on 2025-09-22 03:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("death_year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(8)],
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=11)),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "publication_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(1500),
                            django.core.validators.MaxValueValidator(2099),
                        ]
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("superb", "Superb"),
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("unrated", "Unrated"),
                        ],
                        default="unrated",
                        max_length=10,
                    ),
                ),
                (
                    "book_status",
                    models.CharField(
                        choices=[
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("available", "Available"),
                            ("processing", "Processing"),
                        ],
                        default="processing",
                        max_length=10,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        default="Unknown",
                        related_name="books",
                        to="book_shop_here.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("mailing_address", models.CharField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("first_name__isnull", False),
                            ("first_name__isnull", True),
                            _connector="OR",
                        ),
                        name="name_required",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("address", models.CharField()),
                ("zip_code", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("hire_date", models.DateField(auto_now_add=True)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_shop_here.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
                ("delivery_pickup_date", models.DateField(blank=True, null=True)),
                ("sale_amount", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("credit", "Credit Card"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_ship", "To Be Shipped"),
                            ("pickup", "Customer Will Pick Up"),
                            ("shipped", "Shipped"),
                            ("picked_up", "Picked Up"),
                        ],
                        default="pickup",
                        max_length=30,
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        related_name="orders", to="book_shop_here.book"
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_shop_here.customer",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_shop_here.employee",
                    ),
                ),
            ],
        ),
    ]
