# Generated by Django 5.2.6 on 2025-09-22 05:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_shop_here", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books", to="book_shop_here.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1500, 1, 1)),
                    django.core.validators.MaxValueValidator(
                        datetime.date(2099, 12, 31)
                    ),
                ]
            ),
        ),
    ]
