# Generated by Agent Mode
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0002_auto_20250927_2050"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
