# Generated by Django 5.2.6 on 2025-09-23 18:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0002_alter_book_authors_alter_book_book_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='name_required',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Author birth year'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Author death year'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Author description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Author first name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Author last name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='book_shop_here.author', verbose_name='Book author(s)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Book cost'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Book edition if applicable'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1500, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2099, 12, 31))], verbose_name='Book pub date (1500 < date < 2099)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(choices=[('superb', 'Superb'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('unrated', 'Unrated')], default='unrated', max_length=10, verbose_name='Visible book condition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Book suggested retail price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Book title'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer first name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer last name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer mailing address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Employee address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Employee first name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Employee hire date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Employee last name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Employee phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shop_here.role', verbose_name='Employee role ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Employee state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee user'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(max_length=50, verbose_name='Employee zip code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shop_here.customer', verbose_name='Customer id for order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shop_here.employee', verbose_name='Employee id for order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date when order was placed'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Role description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Role title'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__isnull', False), ('last_name__isnull', False), _connector='OR'), name='name_required'),
        ),
    ]
