# Generated by Django 5.2.6 on 2025-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_shop_here",
            "0002_alter_author_birth_year_alter_author_death_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                default="Unknown", related_name="books", to="book_shop_here.author"
            ),
        ),
    ]
