# Generated by Django 5.2.6 on 2025-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_shop_here", "0003_alter_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
