# Generated by Django 5.2.6 on 2025-09-23 20:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0003_remove_customer_name_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=datetime.date(1600, 1, 1), verbose_name='Employee date of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Book edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1500, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2099, 12, 31))], verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Suggested retail price'),
        ),
    ]
