# Generated by Django 5.2.6 on 2025-09-24 04:50

import book_shop_here.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_shop_here", "0004_employee_birth_date_alter_author_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.CharField(
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    book_shop_here.models.validate_book_id,
                ],
            ),
        ),
    ]
