# Generated by Agent Mode
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0004_add_report_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="condition_notes",
            field=models.TextField(
                blank=True, null=True, max_length=1000, verbose_name="Condition notes"
            ),
        ),
    ]
