# Generated by Django 5.2.6 on 2025-09-25 03:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_shop_here", "0005_alter_book_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Book publisher"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="author_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Author first name",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1600, 1, 1)),
                    django.core.validators.MaxValueValidator(
                        datetime.date(2099, 12, 31)
                    ),
                ],
                verbose_name="Publication Date",
            ),
        ),
    ]
