# Generated by Django 5.2.7 on 2025-10-09 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0005_add_condition_notes_to_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("view_sales_reports", "Can view sales reports"),
                    ("view_employee_sales", "Can view employee sales"),
                ]
            },
        ),
    ]
