# Generated by Django 5.2.6 on 2025-09-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("book_shop_here", "0006_book_publisher_alter_author_author_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="group",
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Role description",
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                verbose_name="Employee role",
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
