# Generated by Django 5.2.7 on 2025-10-15 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0006_alter_order_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="rating",
            new_name="condition",
        ),
    ]
