# Generated by Django 5.2.7 on 2025-10-16 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0007_rename_rating_book_condition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="retail_price",
            new_name="suggested_retail_price",
        ),
    ]
