# Generated by Django 5.2.6 on 2025-09-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_shop_here", "0008_auto_20250925_0927"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="position_id",
            new_name="group",
        ),
    ]
