# Generated by Django 5.2.7 on 2025-10-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0008_rename_retail_price_book_suggested_retail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="secondary_mailing_address",
            field=models.CharField(
                blank=True,
                default="N/A",
                max_length=200,
                verbose_name="Customer secondary address",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="secondary_address",
            field=models.CharField(
                blank=True,
                default="N/A",
                max_length=200,
                verbose_name="Employee secondary address",
            ),
        ),
    ]
