# Generated by Django 5.2.6 on 2025-09-25 19:22

from django.db import migrations

def add_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    owner_group = Group.objects.get(name='Owner')
    assistant_manager_group = Group.objects.get(name='Assistant Manager')
    
    perms_to_assign = Permission.objects.filter(codename__in=['add_group', 'change_group', 'delete_group', 'view_group'])
    owner_group.permissions.add(*perms_to_assign)
    owner_group.save
    assistant_manager_group.permissions.add(*perms_to_assign)
    assistant_manager_group.save

def remove_added_permissions(apps, schema_editor):
    """Reverses the creation of the groups."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    owner_group = Group.objects.get(name='Owner')
    assistant_manager_group = Group.objects.get(name='Assistant Manager')
    
    perms_to_remove = Permission.objects.filter(codename__in=['add_group', 'change_group', 'delete_group', 'view_group'])
    owner_group.permissions.remove(*perms_to_remove)
    assistant_manager_group.permissions.remove(*perms_to_remove)

class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0009_rename_position_id_employee_group'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, remove_added_permissions),
    ]
