# Generated by Django 5.2.6 on 2025-09-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0010_auto_20250925_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Employee email'),
        ),
    ]
