# Generated by Django 5.2.6 on 2025-09-27 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("book_shop_here", "0011_employee_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="legacy_id",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Legacy book ID"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                db_index=True, max_length=500, verbose_name="Book title"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Employee hire date"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employee user",
            ),
        ),
        migrations.AlterField(
            model_name="groupprofile",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to="auth.group",
            ),
        ),
    ]
