# Generated by Django 5.2.7 on 2025-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0011_alter_book_book_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='name_required',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer state'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer zip code'),
        ),
    ]
