# Generated by Django 5.2.7 on 2025-10-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_here', '0012_remove_customer_name_required_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='No City', max_length=50, verbose_name='Employee city'),
            preserve_default=False,
        ),
    ]
