# Generated by Django 5.2.7 on 2025-12-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_shop_here", "0013_employee_city"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("first_name__isnull", False), ("last_name__isnull", False), _connector="OR"
                ),
                name="name_required",
            ),
        ),
    ]
